.param pW1 = 4.029e-03
.param pW2 = 9.005e-04
.param pW3 = 3.039e-03
.param pW4 = 2.686e-03
.param pW5 = 5.000e-03
.param pW6 = 6.126e-04
.param pL1 = 8.867e-07
.param pL2 = 7.806e-07
.param pL3 = 8.292e-07
.param pL4 = 8.062e-07
.param pL5 = 9.155e-07
.param pL6 = 7.624e-07
.param pIbias = 3.938e-03
.param pCmu = 7.697e-12

.param pCload = 1.000e-11
.param pVdd = 3.000e+00
.param pVdcin = 1.500e+00
.param pVout = 1.500e+00
.param pRfb = 1.000e+09
.param pCfb = 1.000e-03

.param pDU01a = 0.0
.param pDNSUB1a = 0.0
.param pDLINT1a = 0.0
.param pDWINT1a = 0.0
.param pDTOX1a = 0.0
.param pDRSH1a = 0.0

.param pDU01b = 0.0
.param pDNSUB1b = 0.0
.param pDLINT1b = 0.0
.param pDWINT1b = 0.0
.param pDTOX1b = 0.0
.param pDRSH1b = 0.0

.param pDU02a = 0.0
.param pDNSUB2a = 0.0
.param pDLINT2a = 0.0
.param pDWINT2a = 0.0
.param pDTOX2a = 0.0
.param pDRSH2a = 0.0

.param pDU02b = 0.0
.param pDNSUB2b = 0.0
.param pDLINT2b = 0.0
.param pDWINT2b = 0.0
.param pDTOX2b = 0.0
.param pDRSH2b = 0.0

.param pDU03 = 0.0
.param pDNSUB3 = 0.0
.param pDLINT3 = 0.0
.param pDWINT3 = 0.0
.param pDTOX3 = 0.0
.param pDRSH3 = 0.0

.param pDU04 = 0.0
.param pDNSUB4 = 0.0
.param pDLINT4 = 0.0
.param pDWINT4 = 0.0
.param pDTOX4 = 0.0
.param pDRSH4 = 0.0

.param pDU05 = 0.0
.param pDNSUB5 = 0.0
.param pDLINT5 = 0.0
.param pDWINT5 = 0.0
.param pDTOX5 = 0.0
.param pDRSH5 = 0.0

.param pDU06 = 0.0
.param pDNSUB6 = 0.0
.param pDLINT6 = 0.0
.param pDWINT6 = 0.0
.param pDTOX6 = 0.0
.param pDRSH6 = 0.0


